id: create_pr_for_access_control
learningObjectives:
  - Fix access controls and open a PR.
hints:
  - Verifying the comment seller user IDs before deletion.
  - Make sure you return a status code of 403 if the user is not the author of the comment.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: I appreciate you sticking out thus far.
          - text: If access controls are indeed broken, I'm going to need you to fix them. Create a new PR and make it
              so only comment authors can delete their comments.
          - text: If you complete this, Ness might bake you a cake. Or maybe not, but you'll have
              her gratitude for sure.
          - text: Let's make sure that only comments that the user wrote can be deleted and if not return a **status code of 403**, :instruction[Open a PR with those changes and I'll review it.]
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: lucca
                message: "Reviewing this right now, let's see..."
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "Got your PR, going over it right now."
                    delay: 100
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "Make sure your fix passes all the checks, then try again please."
                    delay: 3000
            - actionId: github_pr_reject
              params:
                person: lucca
                message: "Looks like this code change didn't resolve the issue. Can you take a second look?"
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "Nice job, go ahead and merge this PR."
                    delay: 2000
            - actionId: github_pr_approve
              params:
                person: lucca
                message: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
        github_pr_merged:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Great job! You've tucked away those loose ends.
                  - text: Our user's data is safer thanks to you. Keep your eye on the ball--and our endpoints.
                  - text: Ness is thanking you in advance for laying her worries to rest.
            - actionId: finish_step
githubActions:
  backend:
    capabilities:
      - axios
      - dotenv
    testFile: "verify_access_control.js"
